name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*-duck*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run linter
        run: yarn lint
        
      - name: Run tests
        run: yarn test
        
      - name: Build minified version
        run: yarn build
        
      - name: Verify build artifacts
        run: |
          ls -la jquery.scrollify.min.js
          ls -la jquery.scrollify.min.js.map
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this Release
            
            ### Files included:
            - `jquery.scrollify.min.js` - Minified production build
            - `jquery.scrollify.min.js.map` - Source map for debugging
            - `jquery.scrollify.js` - Unminified source code
            
            ### Installation
            ```html
            <!-- CDN -->
            <script src="https://github.com/duckcoinorg/Scrollify/releases/download/${{ github.ref_name }}/jquery.scrollify.min.js"></script>
            
            <!-- Or download and host locally -->
            ```
            
            ### Usage
            ```javascript
            $(function() {
                $.scrollify({
                    section: ".section"
                });
            });
            ```
          draft: false
          prerelease: false
          
      - name: Upload minified JS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./jquery.scrollify.min.js
          asset_name: jquery.scrollify.min.js
          asset_content_type: application/javascript
          
      - name: Upload source map
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./jquery.scrollify.min.js.map
          asset_name: jquery.scrollify.min.js.map
          asset_content_type: application/json
          
      - name: Upload source JS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./jquery.scrollify.js
          asset_name: jquery.scrollify.js
          asset_content_type: application/javascript 